version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mi_mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: sismografo
    ports:
      - "3306:3306" 
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: